pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - "#approved-reviews-by>=0"
      - status-success=Travis CI - Pull Request
      - label!=work-in-progress
    actions:
      merge:
        method: merge
