pull_request_rules:
  - name: Travis CI - Pull Request
    conditions:
      - "#approved-reviews-by>=0"
      - status-success=continuous-integration/travis-ci/pr
      - label!=work-in-progress
    actions:
      merge:
        method: merge
