language: generic
sudo: required

notifications:
  email: false

before_script:
  - chmod +x devops/scripts/check-target-changes.sh
  - chmod +x devops/scripts/ci.run-target.lint.sh
  - chmod +x devops/scripts/ci.run-target.test.sh
  - chmod +x devops/scripts/auto_merge.sh
  - chmod +x devops/scripts/ci.lint.sh
  - chmod +x devops/scripts/ci.test.sh
  - chmod +x devops/scripts/ci.build-target.docker-hub.sh
  - chmod +x devops/scripts/ci.build.docker-hub.sh
  - chmod +x devops/scripts/ci.build-target.ecr.sh
  - chmod +x devops/scripts/ci.init-build.ecr.sh
  - chmod +x devops/scripts/ci.heroku-deploy.sh
  - chmod +x devops/scripts/ci.heroku-deploy-target.sh

branches:
  only:
    - master

env:
  global:
    - APPS=client/auth-service/products-service

jobs:
  include:
    - stage: CI CHEKS
      if: type = pull_request
      name: "Linting"
      script: ./devops/scripts/ci.lint.sh
    - script: ./devops/scripts/ci.test.sh
      if: type = pull_request
      name: "Testing"
    - stage: Deploy to Heroku
      if: type = push
      script: ./devops/scripts/ci.heroku-deploy.sh

cache: npm
