language: generic
sudo: required

notifications:
  email: false

before_script:
  - chmod +x devops/scripts/check-target-changes.sh
  - chmod +x devops/scripts/ci.run-target.sh
  - chmod +x devops/scripts/ci.run-all.sh
  - chmod +x devops/scripts/auto_merge.sh
  - chmod +x devops/scripts/after_success.sh

branches:
  only:
    - master
matrix:
  include:
    - env: TARGET=client
    - env: TARGET=auth-service
    - env: TARGET=products-service

script: ./devops/scripts/ci.run-all.sh

after_success:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
    if [ "$BUILD_LEADER" = "YES" ]; then
      if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
        echo "All jobs succeeded! PUBLISHING..."
      else
        echo "Some jobs failed"
      fi
    fi
after_failure:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
    if [ "$BUILD_LEADER" = "YES" ]; then
      if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
        echo "All jobs failed"
      else
        echo "Some jobs failed"
      fi
    fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
