language: generic
sudo: required

notifications:
  email: false

before_script:
  - chmod +x devops/scripts/check-target-changes.sh
  - chmod +x devops/scripts/ci.run-target.sh
  - chmod +x devops/scripts/ci.run-all.sh
  - chmod +x devops/scripts/auto_merge.sh
  - chmod +x devops/scripts/after_success.sh

branches:
  only:
    - master
matrix:
  include:
    - env: TARGET=client
    - env: TARGET=auth-service
    - env: TARGET=products-service

script: ./devops/scripts/ci.run-all.sh

