language: node_js189d7f0ef63aa17bdca9c557a5827906d9cdcf20

node_js:
  - 10

script:
  - npm run ci:install
  - npm run ci:lint
  - npm run ci:test

after_success:
  - npm run ci:auto:merge


cache: npm
