language: generic
sudo: required

notifications:
  email: false

before_script:
  - chmod +x devops/scripts/build-condition.sh
  - chmod +x devops/scripts/ci.lint.split.sh

branches:
  only:
    - master
matrix:
  include:
    - env: TARGET=client
    - env: TARGET=auth-service
    - env: TARGET=products-service

script: if ./devops/scripts/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then ./devops/scripts/ci.lint.split.sh $TARGET; else echo "$TARGET is NOT being built"; fi
