sudo: required

language: node_js

node_js:
  - 10

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
#  - mkdir -p ~/shared
#  - aws s3 sync s3://travis-build-stages-shared-storage-test/shared ~/shared

#script:
#  - npm run ci:install
#  - npm run ci:lint
#  - npm run ci:test

jobs:
  include:
    - stage: install
      script: npm run ci:install:client
    - script: npm run ci:install:products
    - script: npm run ci:install:auth

    - stage: lint
      script: npm run ci:lint:client
    - script: npm run ci:lint:products
    - script: npm run ci:lint:auth

    - stage: test
      script: npm run ci:test:client

stages:
  - install
  - lint

after_success:
  - npm run ci:publish:products:docker:hub
  - npm run ci:publish:auth:ecr


cache: npm
