language: node_js189d7f0ef63aa17bdca9c557a5827906d9cdcf20

node_js:
  - 10

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - npm run ci:install
  - npm run ci:lint
  - npm run ci:test

after_success:
  - npm run ci:publish:docker:hub
  - npm run ci:publish:ecr


cache: npm
