language: generic
sudo: required

notifications:
  email: false

before_script:
  - chmod +x devops/scripts/check-target-changes.sh
  - chmod +x devops/scripts/ci.run-target.lint.sh
  - chmod +x devops/scripts/ci.run-target.test.sh
  - chmod +x devops/scripts/auto_merge.sh
  - chmod +x devops/scripts/ci.lint.sh
  - chmod +x devops/scripts/ci.test.sh
  - chmod +x devops/scripts/ci.build-target.docker-hub.sh
  - chmod +x devops/scripts/ci.build.docker-hub.sh
  - chmod +x devops/scripts/ci.build-target.ecr.sh
  - chmod +x devops/scripts/ci.init-build.ecr.sh
  - chmod +x devops/scripts/ci.heroku-deploy.sh
  - chmod +x devops/scripts/ci.heroku-deploy-target.sh

branches:
  only:
    - master

env:
  global:
    - APPS=client, auth-service, products-service

jobs:
  include:
#    - stage: lint
#      if: type = pull_request
#      name: "Linting"
#      script: ./devops/scripts/ci.lint.sh client
    - stage: test
      if: type = pull_request
      name: "Testing"
      script: ./devops/scripts/ci.test.sh client
    - stage: build to DOCKER HUB
      if: type = push
      name: "Building client app"
      script: ./devops/scripts/ci.build.docker-hub.sh client
    - script: ./devops/scripts/ci.build.docker-hub.sh auth-service
      name: "Building auth-service app"
      if: type = push
    - script: ./devops/scripts/ci.build.docker-hub.sh products-service
      name: "Building products-service app"
      if: type = push
    - stage: build to ECR
      if: type = push
      name: "Building client app"
      script: ./devops/scripts/ci.init-build.ecr.sh client
    - script: ./devops/scripts/ci.init-build.ecr.sh auth-service
      name: "Building auth-service app"
      if: type = push
    - script: ./devops/scripts/ci.init-build.ecr.sh products-service
      name: "Building products-service app"
      if: type = push
    - stage: Deploy to Heroku
      if: type = push
      name: "Deploy client app"
      script: ./devops/scripts/ci.heroku-deploy.sh client
    - script: ./devops/scripts/ci.heroku-deploy.sh auth-service
      name: "Deploy auth-service app"
      if: type = push
    - script: ./devops/scripts/ci.heroku-deploy.sh products-service
      name: "Deploy products-service app"
      if: type = push

cache: npm
