sudo: required

language: node_js

node_js:
  - 10

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - npm run ci:install
  - npm run ci:lint
  - npm run ci:test

after_success:
  - npm run ci:publish:products:docker:hub
  - npm run ci:publish:auth:ecr


cache: npm
