version: "2"
services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3000"
    environment:
      - PRODUCTS_API_URL=http://localhost:4001
      - NODE_ENV=development
    depends_on:
      - products-service
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
  products-service:
    build: ./products-service
    ports:
      - "4001:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGO_DB_URI_PRODUCTS=mongodb://db/ci-cd-products
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - PORT=5000
      - MONGO_DB_URI_AUTH=mongodb://db/ci-cd-auth
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
