version: "3"
services:
  web:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/ci-cd-products
  mongo:
    image: mongo
    ports:
      - "27017:27017"
