version: "2"
services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./enviroment/local.env
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
